// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: api/API.kt
// Package: com.lightningkite.butterflytemplate.api
import { APIOnline } from './APIOnline'
import { APIInterface } from './APIInterface'

//! Declares com.lightningkite.butterflytemplate.api.API
export let _API: APIInterface = new APIOnline(undefined);
export function getAPI(): APIInterface { return _API; }
export function setAPI(value: APIInterface) { _API = value; }


