// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: api/API.shared.kt
// Package: com.lightningkite.khrysalistemplate.api
// FQImport: com.lightningkite.khrysalistemplate.api.APIOnline TS APIOnline
// FQImport: com.lightningkite.khrysalistemplate.api.APIInterface TS APIInterface
import { APIInterface } from './APIInterface.shared'
import { APIOnline } from './APIOnline.shared'

//! Declares com.lightningkite.khrysalistemplate.api.API
export let _API: APIInterface = new APIOnline(undefined);
export function getAPI(): APIInterface { return _API; }
export function setAPI(value: APIInterface) { _API = value; }


