//! This file will translate using Butterfly.
// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: api/API.shared.kt
// Package: com.lightningkite.butterflytemplate.api
import { APIInterface } from './APIInterface.shared'
import { APIOnline } from './APIOnline.shared'

//! Declares com.lightningkite.butterflytemplate.api.API
export let _API: APIInterface = new APIOnline(undefined);
export function getAPI(): APIInterface { return _API; }
export function setAPI(value: APIInterface) { _API = value; }


