// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: api/APIInterface.kt
// Package: com.lightningkite.butterflytemplate.api
import { Post } from '../models/Post'
import { Observable } from 'rxjs'

//! Declares com.lightningkite.butterflytemplate.api.APIInterface
export interface APIInterface {
    
    getExamplePosts(): Observable<Array<Post>> 
}


