//! This file will translate using Butterfly.
// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: api/APIInterface.shared.kt
// Package: com.lightningkite.butterflytemplate.api
import { Post } from '../models/Post.shared'
import { Observable } from 'rxjs'

//! Declares com.lightningkite.butterflytemplate.api.APIInterface
export interface APIInterface {
    
    getExamplePosts(): Observable<Array<Post>> 
}


