//! This file will translate using Butterfly.
// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: api/APIMock.shared.kt
// Package: com.lightningkite.butterflytemplate.api
import { Post } from '../models/Post.shared'
import { delay as rxDelay } from 'rxjs/operators'
import { Observable, of as rxOf } from 'rxjs'
import { APIInterface } from './APIInterface.shared'

//! Declares com.lightningkite.butterflytemplate.api.APIMock
export class APIMock implements APIInterface {
    public static implementsInterfaceComLightningkiteButterflytemplateApiAPIInterface = true;
    public constructor() {
    }
    
    
    
    
    public getExamplePosts(): Observable<Array<Post>> {
        return rxOf([new Post(undefined, undefined, "First", APIMock.Companion.INSTANCE.lorem)]).pipe(rxDelay(1000));
    }
}
export namespace APIMock {
    //! Declares com.lightningkite.butterflytemplate.api.APIMock.Companion
    export class Companion {
        private constructor() {
            this.delayMs = 150;
            this.lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
        }
        public static INSTANCE = new Companion();
        
        public delayMs: number;
        
        public readonly lorem: string;
        
    }
}

