//! This file will translate using Butterfly.
// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: api/APIOnline.shared.kt
// Package: com.lightningkite.butterflytemplate.api
import { xSingleReadJson } from 'butterfly/dist/net/RxHttpAssist.actual'
import { Post } from '../models/Post.shared'
import { Observable } from 'rxjs'
import { HttpClient } from 'butterfly/dist/net/HttpClient.actual'
import { APIInterface } from './APIInterface.shared'

//! Declares com.lightningkite.butterflytemplate.api.APIOnline
export class APIOnline implements APIInterface {
    public static implementsInterfaceComLightningkiteButterflytemplateApiAPIInterface = true;
    public readonly baseUrl: string;
    public constructor(baseUrl: string = "https://jsonplaceholder.typicode.com") {
        this.baseUrl = baseUrl;
    }
    
    public getExamplePosts(): Observable<Array<Post>> {
        return xSingleReadJson<Array<Post>>(HttpClient.INSTANCE.call(this.baseUrl + "/posts", HttpClient.INSTANCE.GET, new Map([]), undefined, undefined), [Array, [Post]]);
    }
    
}

