// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: api/API.kt
// Package: com.lightningkite.butterflytemplate.api
import Butterfly
import Foundation

public var API: APIInterface = APIOnline()


