// File: /home/jivie/Projects/khrysalis-template/android/src/main/java/com/lightningkite/butterflytemplate/api/API.kt
// Package: com.lightningkite.butterflytemplate.api
// Generated by Khrysalis - this file will be overwritten.
import LKButterfly
import Foundation

public var API: APIInterface = APIOnline()

