// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: api/APIInterface.kt
// Package: com.lightningkite.butterflytemplate.api
import RxSwift
import Butterfly
import Foundation

public protocol APIInterface: AnyObject {
    
    func getExamplePosts() -> Single<Array<Post>> 
}



