// File: /home/jivie/Projects/khrysalis-template/android/src/main/java/com/lightningkite/butterflytemplate/api/APIOnline.kt
// Package: com.lightningkite.butterflytemplate.api
// Generated by Khrysalis - this file will be overwritten.
import RxSwift
import LKButterfly
import Foundation

public class APIOnline : APIInterface {
    public var baseUrl: String
    public init(baseUrl: String = "https://jsonplaceholder.typicode.com") {
        self.baseUrl = baseUrl
        //Necessary properties should be initialized now
    }
    
    public func getExamplePosts() -> Single<Array<Post>> {
        return HttpClient.INSTANCE.call(url: self.baseUrl + "/posts", method: HttpClient.INSTANCE.GET, headers: dictionaryOf()).readJson()
    }
    
}

