// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/DateButtonDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
// FQImport: java.util.Date TS Date
// FQImport: com.lightningkite.khrysalistemplate.vg.DateButtonDemoVG.generate.<anonymous>.it TS it
// FQImport: com.lightningkite.khrysalis.time.format>java.util.Date TS javaUtilDateFormat
// FQImport: com.lightningkite.khrysalistemplate.layouts.DateButtonDemoXml.text TS text
// FQImport: com.lightningkite.khrysalistemplate.layouts.DateButtonDemoXml.setup TS setup
// FQImport: com.lightningkite.khrysalis.time.ClockPartSize.Medium TS Medium
// FQImport: com.lightningkite.khrysalis.time.ClockPartSize TS ClockPartSize
// FQImport: com.lightningkite.khrysalistemplate.layouts.DateButtonDemoXml.dateButton TS dateButton
// FQImport: com.lightningkite.khrysalis.observables.binding.bind>com.lightningkite.khrysalis.views.android.DateButton TS comLightningkiteKhrysalisViewsAndroidDateButtonBind
// FQImport: com.lightningkite.khrysalistemplate.layouts.DateButtonDemoXml TS DateButtonDemoXml
// FQImport: com.lightningkite.khrysalistemplate.vg.DateButtonDemoVG.generate.xml TS xml
// FQImport: com.lightningkite.khrysalis.views.ViewGenerator TS ViewGenerator
// FQImport: com.lightningkite.khrysalistemplate.vg.DateButtonDemoVG.generate.dependency TS dependency
// FQImport: com.lightningkite.khrysalis.observables.StandardObservableProperty TS StandardObservableProperty
// FQImport: com.lightningkite.khrysalistemplate.layouts.DateButtonDemoXml.timeButton TS timeButton
// FQImport: com.lightningkite.khrysalis.observables.binding.bindString>android.widget.TextView TS androidWidgetTextViewBindString
// FQImport: com.lightningkite.khrysalis.observables.binding.bind>com.lightningkite.khrysalis.views.android.TimeButton TS comLightningkiteKhrysalisViewsAndroidTimeButtonBind
// FQImport: com.lightningkite.khrysalis.observables.MutableObservableProperty TS MutableObservableProperty
// FQImport: com.lightningkite.khrysalis.observables.map>com.lightningkite.khrysalis.observables.ObservableProperty<kotlin.Any> TS comLightningkiteKhrysalisObservablesObservablePropertyMap
// FQImport: com.lightningkite.khrysalistemplate.vg.DateButtonDemoVG.date TS date
// FQImport: com.lightningkite.khrysalistemplate.vg.DateButtonDemoVG.generate.view TS view
import { DateButtonDemoXml } from '../layout/DateButtonDemoXml'
import { MutableObservableProperty } from 'khrysalis/dist/observables/MutableObservableProperty.shared'
import { StandardObservableProperty } from 'khrysalis/dist/observables/StandardObservableProperty.shared'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { comLightningkiteKhrysalisObservablesObservablePropertyMap } from 'khrysalis/dist/observables/TransformedObservableProperty.shared'
import { androidWidgetTextViewBindString } from 'khrysalis/dist/observables/binding/TextView.binding.actual'
import { comLightningkiteKhrysalisViewsAndroidDateButtonBind, comLightningkiteKhrysalisViewsAndroidTimeButtonBind } from 'khrysalis/dist/observables/binding/DateButton.binding.actual'
import { javaUtilDateFormat } from 'khrysalis/dist/time/Date.actual'
import { ClockPartSize } from 'khrysalis/dist/time/ClockPartSize.shared'

//! Declares com.lightningkite.khrysalistemplate.vg.DateButtonDemoVG
export class DateButtonDemoVG extends ViewGenerator {
    public constructor() {
        super();
        this.date = new StandardObservableProperty(new Date(), undefined);
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.DateButtonDemoVG.title
    public get title(): string { return "Date Button Demo"; }
    
    
    public readonly date: MutableObservableProperty<Date>;
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new DateButtonDemoXml();
        
        const view = xml.setup(dependency);
        
        
        androidWidgetTextViewBindString(xml.text, comLightningkiteKhrysalisObservablesObservablePropertyMap(this.date, (it) => javaUtilDateFormat(it, ClockPartSize.Medium, ClockPartSize.Medium)));
        comLightningkiteKhrysalisViewsAndroidDateButtonBind(xml.dateButton, this.date);
        comLightningkiteKhrysalisViewsAndroidTimeButtonBind(xml.timeButton, this.date, undefined);
        
        return view;
    }
}

