// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/DateButtonDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
import { DateButtonDemoXml } from '../layout/DateButtonDemoXml'
import { MutableObservableProperty } from 'khrysalis/dist/observables/MutableObservableProperty.shared'
import { StandardObservableProperty } from 'khrysalis/dist/observables/StandardObservableProperty.shared'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { comLightningkiteKhrysalisObservablesObservablePropertyMap } from 'khrysalis/dist/observables/TransformedObservableProperty.shared'
import { androidWidgetTextViewBindString } from 'khrysalis/dist/observables/binding/TextView.binding.actual'
import { comLightningkiteKhrysalisViewsAndroidDateButtonBind, comLightningkiteKhrysalisViewsAndroidTimeButtonBind } from 'khrysalis/dist/observables/binding/DateButton.binding.actual'
import { javaUtilDateFormat } from 'khrysalis/dist/time/Date.actual'
import { ClockPartSize } from 'khrysalis/dist/time/ClockPartSize.shared'

//! Declares com.lightningkite.khrysalistemplate.vg.DateButtonDemoVG
export class DateButtonDemoVG extends ViewGenerator {
    public constructor() {
        super();
        this.date = new StandardObservableProperty<Date>(new Date(), undefined);
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.DateButtonDemoVG.title
    public get title(): string { return "Date Button Demo"; }
    
    
    public readonly date: MutableObservableProperty<Date>;
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new DateButtonDemoXml();
        
        const view = xml.setup(dependency);
        
        
        androidWidgetTextViewBindString(xml.text, comLightningkiteKhrysalisObservablesObservablePropertyMap<Date, string>(this.date, (it: Date): string => javaUtilDateFormat(it, ClockPartSize.Medium, ClockPartSize.Medium)));
        comLightningkiteKhrysalisViewsAndroidDateButtonBind(xml.dateButton, this.date);
        comLightningkiteKhrysalisViewsAndroidTimeButtonBind(xml.timeButton, this.date, undefined);
        
        return view;
    }
}

