// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/DateRangeDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
import { DateRangeDemoXml } from '../layout/DateRangeDemoXml'
import { EqualOverrideSet } from 'khrysalis/dist/KotlinCollections'
import { StandardObservableProperty } from 'khrysalis/dist/observables/StandardObservableProperty.shared'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { numberToColor } from 'khrysalis/dist/views/Colors.actual'

//! Declares com.lightningkite.khrysalistemplate.vg.DateRangeDemoVG
export class DateRangeDemoVG extends ViewGenerator {
    public constructor() {
        super();
        this.start = new StandardObservableProperty(new Date(), undefined);
        this.endInclusive = new StandardObservableProperty(new Date(), undefined);
        this.dates = new StandardObservableProperty(new EqualOverrideSet([]), undefined);
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.DateRangeDemoVG.title
    public get title(): string { return "Date Range Demo"; }
    
    
    public readonly start: StandardObservableProperty<(Date | null)>;
    
    public readonly endInclusive: StandardObservableProperty<(Date | null)>;
    
    public readonly dates: StandardObservableProperty<Set<Date>>;
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new DateRangeDemoXml();
        
        const view = xml.setup(dependency);
        
        
        
        xml.month2Delegate.dragEnabled = false;
        xml.month2Delegate.selectedDayPaint.color = numberToColor(0xFFFFFFFF);
        xml.month2Delegate.selectedPaint.color = numberToColor(0xFFFF0000);
        xml.month3Delegate.dragEnabled = false;
        xml.month3Delegate.selectedDayPaint.color = numberToColor(0xFFFFFFFF);
        xml.month3Delegate.selectedPaint.color = numberToColor(0xFFFF0000);
        xml.month4Delegate.dragEnabled = false;
        xml.month4Delegate.selectedDayPaint.color = numberToColor(0xFFFFFFFF);
        xml.month4Delegate.selectedPaint.color = numberToColor(0xFFFF0000);
        
        return view;
    }
    
}

