//! This file will translate using Butterfly.
// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: vg/ExampleContentVG.shared.kt
// Package: com.lightningkite.butterflytemplate.vg
import { ExampleContentXml } from '../layout/ExampleContentXml'
import { MutableObservableProperty } from 'butterfly/dist/observables/MutableObservableProperty.shared'
import { StandardObservableProperty } from 'butterfly/dist/observables/StandardObservableProperty.shared'
import { ViewGenerator } from 'butterfly/dist/views/ViewGenerator.shared'
import { xTextViewBindString, xTextViewBindText } from 'butterfly/dist/observables/binding/TextView.binding.actual'
import { xObservablePropertyFlatMap } from 'butterfly/dist/observables/FlatMappedObservableProperty.shared'
import { xObservablePropertyMap } from 'butterfly/dist/observables/TransformedObservableProperty.shared'
import { ObservableProperty } from 'butterfly/dist/observables/ObservableProperty.shared'

//! Declares com.lightningkite.butterflytemplate.vg.ExampleContentVG
export class ExampleContentVG extends ViewGenerator {
    public constructor() {
        super();
        this._number = new StandardObservableProperty<number>(0, undefined);
        this.chained = new StandardObservableProperty<MutableObservableProperty<number>>(new StandardObservableProperty<number>(0, undefined), undefined);
    }
    
    //! Declares com.lightningkite.butterflytemplate.vg.ExampleContentVG.title
    public get title(): string { return "Example Content"; }
    
    
    public readonly _number: StandardObservableProperty<number>;
    
    public readonly chained: StandardObservableProperty<MutableObservableProperty<number>>;
    
    
    public increment(): void {
        const temp4 = this._number;
        temp4.value = temp4.value + 1;
    }
    
    public generate(dependency: Window): HTMLElement {
        const xml = new ExampleContentXml();
        
        const view = xml.setup(dependency);
        
        xml.exampleContentIncrement.onclick = (_ev) => { _ev.stopPropagation(); 
            this.increment();
        };
        xTextViewBindText<number>(xml.exampleContentNumber, this._number, (it: number): string => it.toString());
        xml.chainedIncrement.onclick = (_ev) => { _ev.stopPropagation(); 
            this.chained.value.value = this.chained.value.value + 1;
        };
        xTextViewBindString(xml.chainedNumber, xObservablePropertyMap<number, string>(xObservablePropertyFlatMap<MutableObservableProperty<number>, number>(this.chained, (it: MutableObservableProperty<number>): ObservableProperty<number> => it), (it: number): string => it.toString()));
        xml.scrollToTop.onclick = (_ev) => { _ev.stopPropagation(); 
            xml.scrollView.scroll(0, 0);
        };
        return view;
    }
}

