// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/LoadImageDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
import { ImageReference, ImageRemoteUrl } from 'khrysalis/dist/Image.shared'
import { comLightningkiteKhrysalisAndroidActivityAccessRequestImageCamera, comLightningkiteKhrysalisAndroidActivityAccessRequestImageGallery, comLightningkiteKhrysalisAndroidActivityAccessRequestImagesGallery } from 'khrysalis/dist/views/ViewDependency.actual'
import { androidWidgetImageViewLoadImage } from 'khrysalis/dist/views/ImageView.actual'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { LoadImageDemoXml } from '../layout/LoadImageDemoXml'

//! Declares com.lightningkite.khrysalistemplate.vg.LoadImageDemoVG
export class LoadImageDemoVG extends ViewGenerator {
    public constructor() {
        super();
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.LoadImageDemoVG.title
    public get title(): string { return "Load Image Demo"; }
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new LoadImageDemoXml();
        
        const view = xml.setup(dependency);
        
        xml.camera.onclick = (_ev) => { _ev.stopPropagation(); 
            comLightningkiteKhrysalisAndroidActivityAccessRequestImageCamera(dependency, undefined, (url: File): void => {
                    androidWidgetImageViewLoadImage(xml.image, new ImageReference(url))
            });
        };
        xml.galleryMultiple.onclick = (_ev) => { _ev.stopPropagation(); 
            comLightningkiteKhrysalisAndroidActivityAccessRequestImagesGallery(dependency, (urls: Array<File>): void => {
                    let temp_118;
                    if ((temp_118 = (urls[0] ?? null)) !== null) { 
                        androidWidgetImageViewLoadImage(xml.image, new ImageReference(temp_118));
                    }
            });
        };
        xml.gallery.onclick = (_ev) => { _ev.stopPropagation(); 
            comLightningkiteKhrysalisAndroidActivityAccessRequestImageGallery(dependency, (url: File): void => {
                    androidWidgetImageViewLoadImage(xml.image, new ImageReference(url))
            });
        };
        xml.loremPixel.onclick = (_ev) => { _ev.stopPropagation(); 
            androidWidgetImageViewLoadImage(xml.image, new ImageRemoteUrl("https://picsum.photos/200"));
        };
        return view;
    }
}

