// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/LoadImageDemoVG.kt
// Package: com.lightningkite.butterflytemplate.vg
import { HttpBody, xImageToHttpBody } from 'butterfly-web/dist/net/HttpBody'
import { xActivityAccessRequestImageCamera, xActivityAccessRequestImageGallery, xActivityAccessRequestImagesGallery } from 'butterfly-web/dist/views/ViewDependency'
import { Image, ImageReference, ImageRemoteUrl } from 'butterfly-web/dist/Image'
import { xDisposableUntil, xViewRemovedGet } from 'butterfly-web/dist/rx/DisposeCondition.ext'
import { xTextViewBindString } from 'butterfly-web/dist/observables/binding/TextView.binding'
import { SubscriptionLike } from 'rxjs'
import { ViewGenerator } from 'butterfly-web/dist/views/ViewGenerator'
import { xObservablePropertySubscribeBy } from 'butterfly-web/dist/observables/ObservableProperty.ext'
import { xImageViewBindImage } from 'butterfly-web/dist/observables/binding/ImageView.binding'
import { xObservablePropertyMap } from 'butterfly-web/dist/observables/TransformedObservableProperty'
import { StandardObservableProperty } from 'butterfly-web/dist/observables/StandardObservableProperty'
import { printStackTrace, runOrNull } from 'butterfly-web/dist/kotlin/Language'
import { LoadImageDemoXml } from '../layout/LoadImageDemoXml'
import { xViewOnClick } from 'butterfly-web/dist/views/View.ext'

//! Declares com.lightningkite.butterflytemplate.vg.LoadImageDemoVG
export class LoadImageDemoVG extends ViewGenerator {
    public constructor() {
        super();
        this.canUpload = new StandardObservableProperty<(boolean | null)>(null, undefined);
        this.currentImage = new StandardObservableProperty<(Image | null)>(null, undefined);
    }
    
    //! Declares com.lightningkite.butterflytemplate.vg.LoadImageDemoVG.title
    public get title(): string { return "Load Image Demo"; }
    
    
    public readonly canUpload: StandardObservableProperty<(boolean | null)>;
    
    public readonly currentImage: StandardObservableProperty<(Image | null)>;
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new LoadImageDemoXml();
        
        const view = xml.setup(dependency);
        
        
        xDisposableUntil<SubscriptionLike>(xObservablePropertySubscribeBy<(Image | null)>(this.currentImage, undefined, undefined, (it: (Image | null)): void => {
                    this.canUpload.value = null;
        }), xViewRemovedGet(view));
        
        xImageViewBindImage(xml.image, this.currentImage);
        xViewOnClick(xml.camera, undefined, (): void => {
                xActivityAccessRequestImageCamera(dependency, undefined, (url: File): void => {
                        this.currentImage.value = new ImageReference(url);
                });
        });
        xViewOnClick(xml.galleryMultiple, undefined, (): void => {
                xActivityAccessRequestImagesGallery(dependency, (urls: Array<File>): void => {
                        const url_18 = (urls[0] ?? null);
                        if (url_18 !== null) { 
                            this.currentImage.value = new ImageReference(url_18);
                        }
                });
        });
        xViewOnClick(xml.gallery, undefined, (): void => {
                xActivityAccessRequestImageGallery(dependency, (url: File): void => {
                        this.currentImage.value = new ImageReference(url);
                });
        });
        xViewOnClick(xml.loremPixel, undefined, (): void => {
                this.currentImage.value = new ImageRemoteUrl("https://picsum.photos/200");
        });
        xViewOnClick(xml.checkCanUpload, undefined, (): void => {
                const i_19 = this.currentImage.value;
                if (i_19 !== null) { 
                    xImageToHttpBody(i_19, undefined, undefined).subscribe((it: HttpBody): void => {
                            this.canUpload.value = true;
                        }, (it: any): void => {
                            printStackTrace(it);
                            this.canUpload.value = false;
                    });
                }
        });
        xTextViewBindString(xml.canUpload, xObservablePropertyMap<(boolean | null), string>(this.canUpload, (it: (boolean | null)): string => it === null ? "Not checked" : it === true ? "Good to go!" : "FAILED!!!"));
        return view;
    }
}

