// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/LoginDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
import { androidWidgetEditTextBindString } from 'khrysalis/dist/observables/binding/EditText.binding.actual'
import { R } from '../R'
import { Form, FormField, comLightningkiteKhrysalisViewsFormFieldMatches, comLightningkiteKhrysalisViewsFormFieldRequired, comLightningkiteKhrysalisViewsViewStringUnless } from 'khrysalis/dist/views/Form.shared'
import { ExampleContentVG } from './ExampleContentVG.shared'
import { androidWidgetCompoundButtonBind } from 'khrysalis/dist/observables/binding/CompoundButton.binding.actual'
import { MutableObservableProperty } from 'khrysalis/dist/observables/MutableObservableProperty.shared'
import { StandardObservableProperty } from 'khrysalis/dist/observables/StandardObservableProperty.shared'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { ObservableStack } from 'khrysalis/dist/observables/ObservableStack.shared'
import { androidWidgetViewFlipperBindLoading } from 'khrysalis/dist/observables/binding/ViewFlipper.binding.actual'
import { LoginDemoXml } from '../layout/LoginDemoXml'
import { delay } from 'khrysalis/dist/delay.actual'
import { ViewStringResource } from 'khrysalis/dist/views/Strings.shared'

//! Declares com.lightningkite.khrysalistemplate.vg.LoginDemoVG
export class LoginDemoVG extends ViewGenerator {
    public readonly stack: ObservableStack<ViewGenerator>;
    public constructor(stack: ObservableStack<ViewGenerator>) {
        super();
        this.stack = stack;
        this.form = new Form();
        this.username = this.form.fieldRes(R._string.username, "", (field) => comLightningkiteKhrysalisViewsFormFieldRequired(field));
        this.password = this.form.fieldRes(R._string.password, "", (field) => comLightningkiteKhrysalisViewsFormFieldRequired(field));
        this.verifyPassword = this.form.fieldRes(R._string.verify_password, "", (field) => comLightningkiteKhrysalisViewsFormFieldRequired(field) ?? comLightningkiteKhrysalisViewsFormFieldMatches(field, this.password));
        this.agree = this.form.fieldRes(R._string.password, false, (field) => comLightningkiteKhrysalisViewsViewStringUnless(new ViewStringResource(R._string.mustAgree), field.value));
        this.loading = new StandardObservableProperty(false, undefined);
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.LoginDemoVG.title
    public get title(): string { return "Log In Demo"; }
    
    
    public readonly form: Form;
    
    public readonly username: FormField<string>;
    
    public readonly password: FormField<string>;
    
    public readonly verifyPassword: FormField<string>;
    
    public readonly agree: FormField<boolean>;
    
    public readonly loading: MutableObservableProperty<boolean>;
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new LoginDemoXml();
        
        const view = xml.setup(dependency);
        
        
        androidWidgetEditTextBindString(xml.username, this.username.observable);
        androidWidgetEditTextBindString(xml.password, this.password.observable);
        androidWidgetEditTextBindString(xml.verifyPassword, this.verifyPassword.observable);
        androidWidgetCompoundButtonBind(xml.agree, this.agree.observable);
        androidWidgetViewFlipperBindLoading(xml.submitLoading, this.loading, undefined);
        xml.submit.onclick = (_ev) => { _ev.stopPropagation(); 
            this.submit();
        };
        
        return view;
    }
    
    private submit(): void {
        this.form.runOrDialog(() => {
                console.log("Submit!");
                this.loading.value = true;
                delay(1000, () => {
                        this.loading.value = false;
                        this.stack?.push(new ExampleContentVG());
                });
        });
    }
}

