// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/MainVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
import { HasBackAction, HasBackActionDefaults } from 'khrysalis/dist/views/HasBackAction.shared'
import { SelectDemoVG } from './SelectDemoVG.shared'
import { MainXml } from '../layout/MainXml'
import { ExampleContentVG } from './ExampleContentVG.shared'
import { ObservableProperty } from 'khrysalis/dist/observables/ObservableProperty.shared'
import { xViewBindVisible } from 'khrysalis/dist/observables/binding/View.binding.actual'
import { EntryPoint } from 'khrysalis/dist/views/EntryPoint.shared'
import { xSwapViewBindStack } from 'khrysalis/dist/observables/binding/SwapView.binding.actual'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { xTextViewBindString } from 'khrysalis/dist/observables/binding/TextView.binding.actual'
import { ObservableStack } from 'khrysalis/dist/observables/ObservableStack.shared'
import { xObservablePropertyMap } from 'khrysalis/dist/observables/TransformedObservableProperty.shared'

//! Declares com.lightningkite.khrysalistemplate.vg.MainVG
export class MainVG extends ViewGenerator implements EntryPoint {
    public static implementsInterfaceComLightningkiteKhrysalisViewsEntryPoint = true;
    public static implementsInterfaceComLightningkiteKhrysalisViewsHasBackAction = true;
    public constructor() {
        super();
        this.stack = new ObservableStack<ViewGenerator>();
        this.shouldBackBeShown = xObservablePropertyMap<Array<ViewGenerator>, boolean>(this.stack, (it: Array<ViewGenerator>): boolean => it.length > 1);
        this.stack.push(new SelectDemoVG(this.stack));
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.MainVG.title
    public get title(): string { return "Main"; }
    
    
    public readonly stack: ObservableStack<ViewGenerator>;
    
    //! Declares com.lightningkite.khrysalistemplate.vg.MainVG.mainStack
    public get mainStack(): (ObservableStack<ViewGenerator> | null) { return this.stack; }
    
    public readonly shouldBackBeShown: ObservableProperty<boolean>;
    
    
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new MainXml();
        
        const view = xml.setup(dependency);
        
        
        xSwapViewBindStack(xml.mainContent, dependency, this.stack);
        xTextViewBindString(xml.title, xObservablePropertyMap<Array<ViewGenerator>, string>(this.stack, (it: Array<ViewGenerator>): string => ((it[it.length - 1] ?? null)?.title ?? null) ?? ""));
        xViewBindVisible(xml.mainBack, this.shouldBackBeShown);
        xml.mainBack.onclick = (_ev) => { _ev.stopPropagation(); 
            this.stack.pop();
        };
        
        return view;
    }
    
    public handleDeepLink(schema: string, host: string, path: string, params: Map<string, string>): void {
        this.stack.push(new ExampleContentVG());
    }
    
    public onBackPressed(): boolean { return HasBackActionDefaults.onBackPressed(this); }
}

