// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/MarginTestVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
// FQImport: com.lightningkite.khrysalis.views.ViewGenerator TS ViewGenerator
// FQImport: com.lightningkite.khrysalistemplate.layouts.MarginTestXml.setup TS setup
// FQImport: com.lightningkite.khrysalistemplate.vg.MarginTestsVG.generate.xml TS xml
// FQImport: com.lightningkite.khrysalistemplate.vg.MarginTestsVG.generate.dependency TS dependency
// FQImport: com.lightningkite.khrysalistemplate.layouts.MarginTestXml.scrollToTop TS scrollToTop
// FQImport: com.lightningkite.khrysalistemplate.layouts.MarginTestXml.scrollView TS scrollView
// FQImport: com.lightningkite.khrysalistemplate.layouts.MarginTestXml TS MarginTestXml
// FQImport: com.lightningkite.khrysalistemplate.vg.MarginTestsVG.generate.view TS view
import { MarginTestXml } from '../layout/MarginTestXml'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'

//! Declares com.lightningkite.khrysalistemplate.vg.MarginTestsVG
export class MarginTestsVG extends ViewGenerator {
    public constructor() {
        super();
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.MarginTestsVG.title
    public get title(): string { return "Margin Tests"; }
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new MarginTestXml();
        
        const view = xml.setup(dependency);
        
        xml.scrollToTop.addEventListener("onclick", (_ev) => { _ev.stopPropagation(); 
                xml.scrollView.scroll(0, 0);
        });
        return view;
    }
}

