// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/MarginTestVG.kt
// Package: com.lightningkite.butterflytemplate.vg
import { MarginTestXml } from '../layout/MarginTestXml'
import { xViewOnClick } from 'butterfly-web/dist/views/View.ext'
import { ViewGenerator } from 'butterfly-web/dist/views/ViewGenerator'

//! Declares com.lightningkite.butterflytemplate.vg.MarginTestsVG
export class MarginTestsVG extends ViewGenerator {
    public constructor() {
        super();
    }
    
    //! Declares com.lightningkite.butterflytemplate.vg.MarginTestsVG.title
    public get title(): string { return "Margin Tests"; }
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new MarginTestXml();
        
        const view = xml.setup(dependency);
        
        xViewOnClick(xml.scrollToTop, undefined, (): void => {
                xml.scrollView.scroll(0, 0);
        });
        return view;
    }
}

