// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/MultipleDemoVG.kt
// Package: com.lightningkite.butterflytemplate.vg
import { RVTypeHandler, recyclerViewBindMultiType } from 'butterfly/dist/observables/binding/RecyclerView.binding'
import { ObservableProperty } from 'butterfly/dist/observables/ObservableProperty'
import { ComponentTextXml } from '../layout/ComponentTextXml'
import { ConstantObservableProperty } from 'butterfly/dist/observables/ConstantObservableProperty'
import { xTextViewBindString } from 'butterfly/dist/observables/binding/TextView.binding'
import { ComponentTestXml } from '../layout/ComponentTestXml'
import { xObservablePropertyMap } from 'butterfly/dist/observables/TransformedObservableProperty'
import { setViewText } from 'butterfly/dist/views/ViewWithText.ext'
import { MultipleDemoXml } from '../layout/MultipleDemoXml'
import { ViewGenerator } from 'butterfly/dist/views/ViewGenerator'

//! Declares com.lightningkite.butterflytemplate.vg.MultipleDemoVG
export class MultipleDemoVG extends ViewGenerator {
    public constructor() {
        super();
        this.data = [1, 2, "3", 4, "5", undefined, "Test", 6] as Array<any>;
    }
    
    //! Declares com.lightningkite.butterflytemplate.vg.MultipleDemoVG.title
    public get title(): string { return "Multiple List Demo"; }
    
    
    public readonly data: Array<any>;
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new MultipleDemoXml();
        
        const view = xml.setup(dependency);
        
        
        recyclerViewBindMultiType(xml.list, dependency, new ConstantObservableProperty<Array<any>>(this.data), (handler: RVTypeHandler): void => {
                handler.handle<number>([Number], 0, (obs: ObservableProperty<number>): HTMLElement => {
                        const cellXml = new ComponentTestXml();
                        
                        const cellView = cellXml.setup(dependency);
                        
                        xTextViewBindString(cellXml.label, xObservablePropertyMap<number, string>(obs, (it: number): string => `The number ${it}`));
                        return cellView;
                });
                handler.handle<string>([String], "", (obs: ObservableProperty<string>): HTMLElement => {
                        const cellXml = new ComponentTestXml();
                        
                        const cellView = cellXml.setup(dependency);
                        
                        xTextViewBindString(cellXml.label, xObservablePropertyMap<string, string>(obs, (it: string): string => `The string '${it}'`));
                        return cellView;
                });
                handler.handle<void>([undefined], undefined, (obs: ObservableProperty<void>): HTMLElement => {
                        const cellXml = new ComponentTextXml();
                        
                        const cellView = cellXml.setup(dependency);
                        
                        setViewText(cellXml.label, "-----");
                        return cellView;
                });
        });
        
        return view;
    }
}

