// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/MultipleDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
import { ComponentTextXml } from '../layout/ComponentTextXml'
import { ComponentTestXml } from '../layout/ComponentTestXml'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { comLightningkiteKhrysalisObservablesObservablePropertyMap } from 'khrysalis/dist/observables/TransformedObservableProperty.shared'
import { MultipleDemoXml } from '../layout/MultipleDemoXml'
import { androidWidgetTextViewBindString } from 'khrysalis/dist/observables/binding/TextView.binding.actual'
import { setViewText } from 'khrysalis/dist/views/ViewWithText.ext.actual'
import { recyclerViewBindMultiType } from 'khrysalis/dist/observables/binding/RecyclerView.binding.actual'
import { ConstantObservableProperty } from 'khrysalis/dist/observables/ConstantObservableProperty.shared'

//! Declares com.lightningkite.khrysalistemplate.vg.MultipleDemoVG
export class MultipleDemoVG extends ViewGenerator {
    public constructor() {
        super();
        this.data = [1, 2, "3", 4, "5", undefined, "Test", 6] as Array<any>;
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.MultipleDemoVG.title
    public get title(): string { return "Multiple List Demo"; }
    
    
    public readonly data: Array<any>;
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new MultipleDemoXml();
        
        const view = xml.setup(dependency);
        
        
        recyclerViewBindMultiType(xml.list, dependency, new ConstantObservableProperty(this.data), (handler) => {
                handler.handle([Number], 0, (obs) => {
                        const cellXml = new ComponentTestXml();
                        
                        const cellView = cellXml.setup(dependency);
                        
                        androidWidgetTextViewBindString(cellXml.label, comLightningkiteKhrysalisObservablesObservablePropertyMap(obs, (it) => `The number ${it}`));
                        return cellView;
                });
                handler.handle([String], "", (obs) => {
                        const cellXml = new ComponentTestXml();
                        
                        const cellView = cellXml.setup(dependency);
                        
                        androidWidgetTextViewBindString(cellXml.label, comLightningkiteKhrysalisObservablesObservablePropertyMap(obs, (it) => `The string '${it}'`));
                        return cellView;
                });
                handler.handle([undefined], undefined, (obs) => {
                        const cellXml = new ComponentTextXml();
                        
                        const cellView = cellXml.setup(dependency);
                        
                        setViewText(cellXml.label, "-----");
                        return cellView;
                });
        });
        
        return view;
    }
}

