// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/PreviewVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
import { SelectDemoXml } from '../layout/SelectDemoXml'
import { ViewPagerDemoXml } from '../layout/ViewPagerDemoXml'
import { MainXml } from '../layout/MainXml'
import { setViewText } from 'khrysalis/dist/views/ViewWithText.ext.actual'
import { getAndroidViewViewRemoved, ioReactivexDisposablesDisposableUntil } from 'khrysalis/dist/rx/DisposeCondition.actual'
import { SliderDemoXml } from '../layout/SliderDemoXml'
import { DateRangeDemoXml } from '../layout/DateRangeDemoXml'
import { ExampleContentXml } from '../layout/ExampleContentXml'
import { androidxViewpagerWidgetViewPagerBindStatic } from 'khrysalis/dist/observables/binding/ViewPager.binding.actual'
import { StandardObservableProperty } from 'khrysalis/dist/observables/StandardObservableProperty.shared'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { SegmentedControlDemoXml } from '../layout/SegmentedControlDemoXml'
import { PreviewXml } from '../layout/PreviewXml'
import { ControlsDemoXml } from '../layout/ControlsDemoXml'
import { LoginDemoXml } from '../layout/LoginDemoXml'
import { comLightningkiteKhrysalisObservablesObservablePropertySubscribeBy } from 'khrysalis/dist/observables/ObservableProperty.ext.shared'

//! Declares com.lightningkite.khrysalistemplate.vg.PreviewVG
export class PreviewVG extends ViewGenerator {
    public constructor() {
        super();
        this.previews = [new PreviewVG.XmlPreview("ControlsDemoXml", (it) => new ControlsDemoXml().setup(it)), new PreviewVG.XmlPreview("DateRangeDemoXml", (it) => new DateRangeDemoXml().setup(it)), new PreviewVG.XmlPreview("ExampleContentXml", (it) => new ExampleContentXml().setup(it)), new PreviewVG.XmlPreview("LoginDemoXml", (it) => new LoginDemoXml().setup(it)), new PreviewVG.XmlPreview("MainXml", (it) => new MainXml().setup(it)), new PreviewVG.XmlPreview("SegmentedControlDemoXml", (it) => new SegmentedControlDemoXml().setup(it)), new PreviewVG.XmlPreview("SelectDemoXml", (it) => new SelectDemoXml().setup(it)), new PreviewVG.XmlPreview("SliderDemoXml", (it) => new SliderDemoXml().setup(it)), new PreviewVG.XmlPreview("ViewPagerDemoXml", (it) => new ViewPagerDemoXml().setup(it))];
        this.previewIndex = new StandardObservableProperty(0, undefined);
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.PreviewVG.title
    public get title(): string { return "Preview"; }
    
    
    
    
    public readonly previews: Array<PreviewVG.XmlPreview>;
    
    
    public readonly previewIndex: StandardObservableProperty<number>;
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new PreviewXml();
        
        const view = xml.setup(dependency);
        
        androidxViewpagerWidgetViewPagerBindStatic(xml.pager, this.previews, this.previewIndex, (it) => it.make(dependency));
        ioReactivexDisposablesDisposableUntil(comLightningkiteKhrysalisObservablesObservablePropertySubscribeBy(this.previewIndex, undefined, undefined, (it) => {
                    setViewText(xml.viewName, this.previews[it].name)
        }), getAndroidViewViewRemoved(view));
        return view;
    }
    
}
export namespace PreviewVG {
    //! Declares com.lightningkite.khrysalistemplate.vg.PreviewVG.XmlPreview
    export class XmlPreview {
        public readonly name: string;
        public readonly make:  (a: Window) => HTMLElement;
        public constructor(name: string, make:  (a: Window) => HTMLElement) {
            this.name = name;
            this.make = make;
        }
    }
}

