// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/SegmentedControlDemoVG.kt
// Package: com.lightningkite.butterflytemplate.vg
import { StandardObservableProperty } from 'butterfly-web/dist/observables/StandardObservableProperty'
import { SegmentedControlDemoXml } from '../layout/SegmentedControlDemoXml'
import { xTabLayoutBindIndex } from 'butterfly-web/dist/observables/binding/TabLayout.binding'
import { ViewGenerator } from 'butterfly-web/dist/views/ViewGenerator'

//! Declares com.lightningkite.butterflytemplate.vg.SegmentedControlDemoVG
export class SegmentedControlDemoVG extends ViewGenerator {
    public constructor() {
        super();
    }
    
    //! Declares com.lightningkite.butterflytemplate.vg.SegmentedControlDemoVG.title
    public get title(): string { return "Segmented Control Demo"; }
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new SegmentedControlDemoXml();
        
        const view = xml.setup(dependency);
        
        
        xTabLayoutBindIndex(xml.tabs, ["A", "B", "C"], new StandardObservableProperty<number>(0, undefined), undefined);
        xTabLayoutBindIndex(xml.tabs2, ["A", "B", "C", "D", "E", "F", "G"], new StandardObservableProperty<number>(0, undefined), undefined);
        
        return view;
    }
}

