// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/SegmentedControlDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
// FQImport: com.lightningkite.khrysalis.views.ViewGenerator TS ViewGenerator
// FQImport: com.lightningkite.khrysalistemplate.vg.SegmentedControlDemoVG.generate.view TS view
// FQImport: com.lightningkite.khrysalis.observables.binding.bind>com.google.android.material.tabs.TabLayout TS comGoogleAndroidMaterialTabsTabLayoutBind
// FQImport: com.lightningkite.khrysalistemplate.vg.SegmentedControlDemoVG.generate.dependency TS dependency
// FQImport: com.lightningkite.khrysalistemplate.vg.SegmentedControlDemoVG.generate.xml TS xml
// FQImport: com.lightningkite.khrysalis.observables.StandardObservableProperty TS StandardObservableProperty
// FQImport: com.lightningkite.khrysalistemplate.layouts.SegmentedControlDemoXml TS SegmentedControlDemoXml
// FQImport: com.lightningkite.khrysalistemplate.layouts.SegmentedControlDemoXml.tabs2 TS tabs2
// FQImport: com.lightningkite.khrysalistemplate.layouts.SegmentedControlDemoXml.setup TS setup
// FQImport: com.lightningkite.khrysalistemplate.layouts.SegmentedControlDemoXml.tabs TS tabs
import { StandardObservableProperty } from 'khrysalis/dist/observables/StandardObservableProperty.shared'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { SegmentedControlDemoXml } from '../layout/SegmentedControlDemoXml'
import { comGoogleAndroidMaterialTabsTabLayoutBind } from 'khrysalis/dist/observables/binding/TabLayout.binding.actual'

//! Declares com.lightningkite.khrysalistemplate.vg.SegmentedControlDemoVG
export class SegmentedControlDemoVG extends ViewGenerator {
    public constructor() {
        super();
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.SegmentedControlDemoVG.title
    public get title(): string { return "Segmented Control Demo"; }
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new SegmentedControlDemoXml();
        
        const view = xml.setup(dependency);
        
        
        comGoogleAndroidMaterialTabsTabLayoutBind(xml.tabs, ["A", "B", "C"], new StandardObservableProperty(0, undefined), undefined);
        comGoogleAndroidMaterialTabsTabLayoutBind(xml.tabs2, ["A", "B", "C", "D", "E", "F", "G"], new StandardObservableProperty(0, undefined), undefined);
        
        return view;
    }
}

