//! This file will translate using Butterfly.
// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: vg/SelectDemoVG.shared.kt
// Package: com.lightningkite.butterflytemplate.vg
import { ExternalTestVG } from './ExternalTestVG.shared'
import { HasBackAction, HasBackActionDefaults } from 'butterfly/dist/views/HasBackAction.shared'
import { SliderDemoVG } from './SliderDemoVG.shared'
import { DrawableDemoVG } from './DrawableDemoVG.shared'
import { PreviewVG } from './PreviewVG.shared'
import { EntryPoint, EntryPointDefaults } from 'butterfly/dist/views/EntryPoint.shared'
import { MultipleDemoVG } from './MultipleDemoVG.shared'
import { ObservableProperty } from 'butterfly/dist/observables/ObservableProperty.shared'
import { SegmentedControlDemoVG } from './SegmentedControlDemoVG.shared'
import { PongDemoVG } from './PongDemoVG.shared'
import { DateButtonDemoVG } from './DateButtonDemoVG.shared'
import { LoadImageDemoVG } from './LoadImageDemoVG.shared'
import { MarginTestsVG } from './MarginTestVG.shared'
import { MapDemoVG } from './MapDemoVG.shared'
import { ControlsDemoVG } from './ControlsDemoVG.shared'
import { VideoDemoVG } from './VideoDemoVG.shared'
import { DateRangeDemoVG } from './DateRangeDemoVG.shared'
import { HttpDemoVG } from './HttpDemoVG.shared'
import { SelectDemoXml } from '../layout/SelectDemoXml'
import { WebsocketDemoVG } from './WebsocketDemoVG.shared'
import { ComponentTestXml } from '../layout/ComponentTestXml'
import { ExampleContentVG } from './ExampleContentVG.shared'
import { xTextViewBindText } from 'butterfly/dist/observables/binding/TextView.binding.actual'
import { LocationDemoVG } from './LocationDemoVG.shared'
import { ConstantObservableProperty } from 'butterfly/dist/observables/ConstantObservableProperty.shared'
import { ViewPagerDemoVG } from './ViewPagerDemoVG.shared'
import { ViewGenerator } from 'butterfly/dist/views/ViewGenerator.shared'
import { LoginDemoVG } from './LoginDemoVG.shared'
import { ObservableStack } from 'butterfly/dist/observables/ObservableStack.shared'
import { xRecyclerViewBind } from 'butterfly/dist/observables/binding/RecyclerView.binding.actual'

//! Declares com.lightningkite.butterflytemplate.vg.SelectDemoVG
export class SelectDemoVG extends ViewGenerator implements EntryPoint {
    public static implementsInterfaceComLightningkiteButterflyViewsEntryPoint = true;
    public static implementsInterfaceComLightningkiteButterflyViewsHasBackAction = true;
    public readonly stack: ObservableStack<ViewGenerator>;
    public constructor(stack: ObservableStack<ViewGenerator>) {
        super();
        this.stack = stack;
        this.options = [new VideoDemoVG(), new WebsocketDemoVG(), new HttpDemoVG(), new ExternalTestVG(), new PongDemoVG(), new MarginTestsVG(), new MultipleDemoVG(), new DateButtonDemoVG(), new MapDemoVG(), new LocationDemoVG(), new LoadImageDemoVG(), new ControlsDemoVG(), new ExampleContentVG(), new ViewPagerDemoVG(this.stack), new SegmentedControlDemoVG(), new SliderDemoVG(), new DateRangeDemoVG(), new LoginDemoVG(this.stack), new DrawableDemoVG(), new PreviewVG()];
    }
    
    //! Declares com.lightningkite.butterflytemplate.vg.SelectDemoVG.title
    public get title(): string { return "Select Demo"; }
    
    
    public readonly options: Array<ViewGenerator>;
    
    
    public selectVG(viewGenerator: ViewGenerator): void {
        this.stack.push(viewGenerator);
    }
    
    public generate(dependency: Window): HTMLElement {
        const xml = new SelectDemoXml();
        
        const view = xml.setup(dependency);
        
        
        xRecyclerViewBind<ViewGenerator>(xml.list, new ConstantObservableProperty<Array<ViewGenerator>>(this.options), this.options[0], (obs: ObservableProperty<ViewGenerator>): HTMLElement => {
                const xml = new ComponentTestXml();
                
                const view = xml.setup(dependency);
                
                xTextViewBindText<ViewGenerator>(xml.label, obs, (it: ViewGenerator): string => it.title);
                xml.button.onclick = (_ev) => { _ev.stopPropagation(); 
                    this.selectVG(obs.value);
                };
                return view;
        });
        
        return view;
    }
    
    //! Declares com.lightningkite.butterflytemplate.vg.SelectDemoVG.mainStack
    public get mainStack(): (ObservableStack<ViewGenerator> | null) { return this.stack; }
    
    public handleDeepLink(schema: string, host: string, path: string, params: Map<string, string>): void { return EntryPointDefaults.handleDeepLink(this, schema, host, path, params); }
    public onBackPressed(): boolean { return HasBackActionDefaults.onBackPressed(this); }
}

