// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/SliderDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.valueDisplay TS valueDisplay
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.generate.<anonymous>.it TS it
// FQImport: com.lightningkite.khrysalis.observables.binding.bind>android.widget.RatingBar TS ratingBarBindMutable
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.ratingDisplayNumber TS ratingDisplayNumber
// FQImport: com.lightningkite.khrysalis.observables.binding.bindText>android.widget.TextView TS androidWidgetTextViewBindText
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.ratingFloat TS ratingFloat
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.obsRatingFloat TS obsRatingFloat
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.ratingDisplayNumberFloat TS ratingDisplayNumberFloat
// FQImport: com.lightningkite.khrysalis.views.ViewGenerator TS ViewGenerator
// FQImport: kotlin.Int.toString TS toString
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.ratingDisplayStarsSmallFloat TS ratingDisplayStarsSmallFloat
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.rating TS rating
// FQImport: com.lightningkite.khrysalis.observables.binding.bindFloat>android.widget.RatingBar TS ratingBarBindFloatMutable
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.generate.dependency TS dependency
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.obsRatingInt.<anonymous>.it TS it
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.setup TS setup
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.obsRatingInt TS obsRatingInt
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.obsRatingFloat.<anonymous>.it TS it
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.generate.view TS view
// FQImport: kotlin.Float.toString TS toString
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.percent TS percent
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.ratingDisplayStarsFloat TS ratingDisplayStarsFloat
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.ratingDisplayStarsSmall TS ratingDisplayStarsSmall
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.ratio TS ratio
// FQImport: com.lightningkite.khrysalis.observables.binding.bind>android.widget.SeekBar TS androidWidgetSeekBarBind
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml TS SliderDemoXml
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.slider TS slider
// FQImport: com.lightningkite.khrysalistemplate.layouts.SliderDemoXml.ratingDisplayStars TS ratingDisplayStars
// FQImport: com.lightningkite.khrysalis.observables.transformed>com.lightningkite.khrysalis.observables.MutableObservableProperty<kotlin.Any> TS comLightningkiteKhrysalisObservablesMutableObservablePropertyTransformed
// FQImport: com.lightningkite.khrysalis.observables.StandardObservableProperty TS StandardObservableProperty
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.generate.xml TS xml
// FQImport: com.lightningkite.khrysalis.observables.MutableObservableProperty TS MutableObservableProperty
// FQImport: com.lightningkite.khrysalistemplate.vg.SliderDemoVG.percent.<anonymous>.it TS it
import { androidWidgetTextViewBindText } from 'khrysalis/dist/observables/binding/TextView.binding.actual'
import { androidWidgetSeekBarBind } from 'khrysalis/dist/observables/binding/SeekBar.binding.actual'
import { MutableObservableProperty } from 'khrysalis/dist/observables/MutableObservableProperty.shared'
import { ratingBarBindFloatMutable, ratingBarBindMutable } from 'khrysalis/dist/observables/binding/RatingBar.binding.actual'
import { StandardObservableProperty } from 'khrysalis/dist/observables/StandardObservableProperty.shared'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { comLightningkiteKhrysalisObservablesMutableObservablePropertyTransformed } from 'khrysalis/dist/observables/TransformedMutableObservableProperty.shared'
import { SliderDemoXml } from '../layout/SliderDemoXml'

//! Declares com.lightningkite.khrysalistemplate.vg.SliderDemoVG
export class SliderDemoVG extends ViewGenerator {
    public constructor() {
        super();
        this.ratio = new StandardObservableProperty(0, undefined);
        this.percent = comLightningkiteKhrysalisObservablesMutableObservablePropertyTransformed(this.ratio, (it) => Math.floor((it * 100)), (it) => it / 100);
        this.obsRatingInt = comLightningkiteKhrysalisObservablesMutableObservablePropertyTransformed(this.ratio, (it) => Math.floor((it * 5)), (it) => it / 5);
        this.obsRatingFloat = comLightningkiteKhrysalisObservablesMutableObservablePropertyTransformed(this.ratio, (it) => it * 5, (it) => it / 5);
    }
    
    //! Declares com.lightningkite.khrysalistemplate.vg.SliderDemoVG.title
    public get title(): string { return "Slider Demo"; }
    
    
    public readonly ratio: StandardObservableProperty<number>;
    
    public readonly percent: MutableObservableProperty<number>;
    
    public readonly obsRatingInt: MutableObservableProperty<number>;
    
    public readonly obsRatingFloat: MutableObservableProperty<number>;
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new SliderDemoXml();
        
        const view = xml.setup(dependency);
        
        
        androidWidgetSeekBarBind(xml.slider, 0, 100, this.percent);
        androidWidgetTextViewBindText(xml.valueDisplay, this.percent, (it) => it.toString());
        
        ratingBarBindMutable(xml.rating, 5, this.obsRatingInt);
        ratingBarBindMutable(xml.ratingDisplayStars, 5, this.obsRatingInt);
        ratingBarBindMutable(xml.ratingDisplayStarsSmall, 5, this.obsRatingInt);
        androidWidgetTextViewBindText(xml.ratingDisplayNumber, this.obsRatingInt, (it) => it.toString());
        
        ratingBarBindFloatMutable(xml.ratingFloat, 5, this.obsRatingFloat);
        ratingBarBindFloatMutable(xml.ratingDisplayStarsFloat, 5, this.obsRatingFloat);
        ratingBarBindFloatMutable(xml.ratingDisplayStarsSmallFloat, 5, this.obsRatingFloat);
        androidWidgetTextViewBindText(xml.ratingDisplayNumberFloat, this.obsRatingFloat, (it) => it.toString());
        
        return view;
    }
}

