//! This file will translate using Butterfly.
// Generated by Butterfly TypeScript converter - this file will be overwritten.
// File: vg/ViewPagerDemoVG.shared.kt
// Package: com.lightningkite.butterflytemplate.vg
import { ViewPagerDemoXml } from '../layout/ViewPagerDemoXml'
import { ComponentTestXml } from '../layout/ComponentTestXml'
import { StandardObservableProperty } from 'butterfly/dist/observables/StandardObservableProperty.shared'
import { ViewGenerator } from 'butterfly/dist/views/ViewGenerator.shared'
import { setViewText } from 'butterfly/dist/views/ViewWithText.ext.actual'
import { xPageIndicatorViewBind } from 'butterfly/dist/observables/binding/PageIndicatorView.binding.actual'
import { ObservableStack } from 'butterfly/dist/observables/ObservableStack.shared'
import { xViewPagerBindStatic } from 'butterfly/dist/observables/binding/ViewPager.binding.actual'

//! Declares com.lightningkite.butterflytemplate.vg.ViewPagerDemoVG
export class ViewPagerDemoVG extends ViewGenerator {
    public readonly stack: ObservableStack<ViewGenerator>;
    public constructor(stack: ObservableStack<ViewGenerator>) {
        super();
        this.stack = stack;
        this.items = ["First", "Second", "Third"];
        this.selectedIndex = new StandardObservableProperty<number>(0, undefined);
    }
    
    //! Declares com.lightningkite.butterflytemplate.vg.ViewPagerDemoVG.title
    public get title(): string { return "View Pager Demo"; }
    
    
    public readonly items: Array<string>;
    
    public readonly selectedIndex: StandardObservableProperty<number>;
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new ViewPagerDemoXml();
        
        const view = xml.setup(dependency);
        
        
        xViewPagerBindStatic<string>(xml.viewPager, this.items, this.selectedIndex, (it: string): HTMLElement => {
                const xml = new ComponentTestXml();
                
                const view = xml.setup(dependency);
                
                setViewText(xml.label, it);
                return view;
        });
        xPageIndicatorViewBind(xml.viewPagerIndicator, this.items.length, this.selectedIndex);
        
        return view;
    }
}

