// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: vg/DrawableDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
import Foundation
import Khrysalis

public class DrawableDemoVG : ViewGenerator {
    override public init() {
        super.init()
        //Necessary properties should be initialized now
    }
    
    override public var title: String {
        get { return "Drawable Demo" }
    }
    
    override public func generate(dependency: ViewDependency) -> View {
        let xml = DrawableDemoXml()
        let view = xml.setup(dependency: dependency)
        
        return view
    }
}


