// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: vg/LoadImageDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
import Foundation
import Khrysalis

public class LoadImageDemoVG : ViewGenerator {
    override public init() {
        super.init()
        //Necessary properties should be initialized now
    }
    
    override public var title: String {
        get { return "Load Image Demo" }
    }
    
    override public func generate(dependency: ViewDependency) -> View {
        let xml = LoadImageDemoXml()
        let view = xml.setup(dependency: dependency)
        xml.camera.onClick(action: { () -> Void in dependency.requestImageCamera(callback: { (url) -> Void in xml.image.loadImage(image: ImageReference(uri: url)) }) })
        xml.galleryMultiple.onClick(action: { () -> Void in dependency.requestImagesGallery(callback: { (urls) -> Void in if let url = (urls.first) { 
                            xml.image.loadImage(image: ImageReference(uri: url))
        } }) })
        xml.gallery.onClick(action: { () -> Void in dependency.requestImageGallery(callback: { (url) -> Void in xml.image.loadImage(image: ImageReference(uri: url)) }) })
        xml.loremPixel.onClick(action: { () -> Void in xml.image.loadImage(image: ImageRemoteUrl(url: "https://picsum.photos/200")) })
        return view
    }
}


