// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: vg/LocationDemoVG.shared.kt
// Package: com.lightningkite.khrysalistemplate.vg
import Foundation
import Khrysalis

public class LocationDemoVG : ViewGenerator {
    override public init() {
        self.locationInfo = (StandardObservableProperty(underlyingValue: nil as LocationResult?) as StandardObservableProperty<LocationResult?>)
        super.init()
        //Necessary properties should be initialized now
    }
    
    override public var title: String {
        get { return "Location Demo" }
    }
    
    public let locationInfo: MutableObservableProperty<LocationResult?>
    
    override public func generate(dependency: ViewDependency) -> View {
        let xml = LocationDemoXml()
        let view = xml.setup(dependency: dependency)
        xml.getLocation.onClick(action: { () -> Void in dependency.requestLocation(accuracyBetterThanMeters: 100.0, timeoutInSeconds: 5.0, onResult: { (location, message) -> Void in 
                        print(message)
                        self.locationInfo.value = location
        }) })
        xml.locationDisplay.bindString(observable: self.locationInfo.transformed(read: { (it) -> String in if let it = it {
                        return "\(it.coordinate)"
                    } else {
                        return "Nothing yet"
        } }))
        return view
    }
}


