// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: vg/ControlsDemoVG.kt
// Package: com.lightningkite.butterflytemplate.vg
import UIKit
import Butterfly
import Foundation

public class ControlsDemoVG : ViewGenerator {
    override public init() {
        self.text = StandardObservableProperty(underlyingValue: "")
        self.options = StandardObservableProperty(underlyingValue: ["Apple", "Banana", "Chili Pepper", "Dragon Fruit"])
        self.number = StandardObservableProperty(underlyingValue: 32)
        super.init()
        //Necessary properties should be initialized now
    }
    
    override public var title: String {
        get { return "Controls Demo" }
    }
    
    public let text: StandardObservableProperty<String>
    public let options: StandardObservableProperty<Array<String>>
    public let number: StandardObservableProperty<Int>
    
    override public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = ControlsDemoXml()
        let view = xml.setup(dependency: dependency)
        
        xml.numberText.bindInteger(observable: self.number)
        xml.editableText.bindString(observable: self.text)
        xml.editableAutoText.bindString(observable: self.text)
        xml.editableAutoText.bind(options: self.options, toString: { (it) -> String in it }, onItemSelected: { (item) -> Void in self.text.value = item })
        xml.editableTextCopy.bindString(observable: self.text)
        xml.editableTextBig.bindString(observable: self.text)
        xml.spinner.bind(options: self.options, selected: self.text)
        
        return view
    }
}


