// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: vg/DrawableDemoVG.kt
// Package: com.lightningkite.butterflytemplate.vg
import UIKit
import Butterfly
import Foundation

public class DrawableDemoVG : ViewGenerator {
    override public init() {
        super.init()
        //Necessary properties should be initialized now
    }
    
    override public var title: String {
        get { return "Drawable Demo" }
    }
    
    override public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = DrawableDemoXml()
        let view = xml.setup(dependency: dependency)
        
        return view
    }
}


