// File: /home/jivie/Projects/khrysalis-template/android/src/main/java/com/lightningkite/butterflytemplate/vg/ExternalTestVG.kt
// Package: com.lightningkite.butterflytemplate.vg
// Generated by Khrysalis - this file will be overwritten.
import UIKit
import LKButterfly
import Foundation

public class ExternalTestVG : ViewGenerator {
    override public init() {
        super.init()
        //Necessary properties should be initialized now
    }
    
    
    
    override public var title: String {
        get { return "External Test" }
    }
    
    override public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = ExternalTestXml()
        let view = xml.setup(dependency: dependency)
        
        //--- Set Up xml.scrollView (overwritten on flow generation)
        
        //--- Set Up xml.openMap
        xml.openMap.onClick(action: { () -> Void in dependency.openMap(coordinate: GeoCoordinate(latitude: 41.7269, longitude: (-111.8432)), label: "Lightning Kite", zoom: 14) })
        
        //--- Set Up xml.openWeb
        xml.openWeb.onClick(action: { () -> Void in dependency.openUrl(url: "https://lightningkite.com") })
        
        //--- Set Up xml.openEvent
        xml.openEvent.onClick(action: { () -> Void in dependency.openEvent(title: "A Virtual Lunch with LK", myDescription: "Come eat virtual food with us!", location: "Lightning Kite in Logan Utah", start: Date().addDayOfMonth(value: 1).hourOfDay(value: 12).minuteOfHour(value: 0).secondOfMinute(value: 0), end: Date().addDayOfMonth(value: 1).hourOfDay(value: 13).minuteOfHour(value: 0).secondOfMinute(value: 0)) })
        
        //--- Generate End (overwritten on flow generation)
        
        return view
    }
    
    //--- Init
    
    
    
    //--- Actions
    
    //--- Action openMapClick
    //--- Action openWebClick
    //--- Action openEventClick
    
    //--- Body End
}

