// File: /home/jivie/Projects/khrysalis-template/android/src/main/java/com/lightningkite/butterflytemplate/vg/MarginTestVG.kt
// Package: com.lightningkite.butterflytemplate.vg
// Generated by Khrysalis - this file will be overwritten.
import UIKit
import LKButterfly
import Foundation

public class MarginTestsVG : ViewGenerator {
    override public init() {
        super.init()
        //Necessary properties should be initialized now
    }
    
    override public var title: String {
        get { return "Margin Tests" }
    }
    
    override public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = MarginTestXml()
        let view = xml.setup(dependency: dependency)
        xml.scrollToTop.onClick(action: { () -> Void in xml.scrollView.smoothScrollTo(0, 0) })
        return view
    }
}

