// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: vg/SegmentedControlDemoVG.kt
// Package: com.lightningkite.butterflytemplate.vg
import Butterfly
import Foundation

public class SegmentedControlDemoVG : ViewGenerator {
    override public init() {
        super.init()
        //Necessary properties should be initialized now
    }
    
    override public var title: String {
        get { return "Segmented Control Demo" }
    }
    
    override public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = SegmentedControlDemoXml()
        let view = xml.setup(dependency: dependency)
        
        xml.tabs.bind(tabs: ["A", "B", "C"], selected: StandardObservableProperty(underlyingValue: 0))
        xml.tabs2.bind(tabs: ["A", "B", "C", "D", "E", "F", "G"], selected: StandardObservableProperty(underlyingValue: 0))
        
        return view
    }
}


