// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: vg/ViewPagerDemoVG.kt
// Package: com.lightningkite.butterflytemplate.vg
import UIKit
import Butterfly
import Foundation

public class ViewPagerDemoVG : ViewGenerator {
    public var stack: ObservableStack<ViewGenerator>
    public init(stack: ObservableStack<ViewGenerator>) {
        self.stack = stack
        self.items = ["First", "Second", "Third"]
        self.selectedIndex = StandardObservableProperty(underlyingValue: 0)
        super.init()
        //Necessary properties should be initialized now
    }
    
    override public var title: String {
        get { return "View Pager Demo" }
    }
    
    public let items: Array<String>
    public let selectedIndex: StandardObservableProperty<Int>
    
    override public func generate(dependency: ViewControllerAccess) -> UIView {
        let xml = ViewPagerDemoXml()
        let view = xml.setup(dependency: dependency)
        
        xml.viewPager.bind(items: self.items, showIndex: self.selectedIndex, makeView: { (it) -> UIView in 
                let xml = ComponentTestXml()
                let view = xml.setup(dependency: dependency)
                xml.label.text = it
                return view
        })
        xml.viewPagerIndicator.bind(count: self.items.count, selected: self.selectedIndex)
        
        return view
    }
}


