// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: api/API.shared.kt
// Package: com.lightningkite.khrysalistemplate.api
import Foundation
import Khrysalis

public var API: APIInterface = APIOnline()


