// Generated by Khrysalis Swift converter - this file will be overwritten.
// File: api/APIInterface.shared.kt
// Package: com.lightningkite.khrysalistemplate.api
import RxSwift
import Foundation
import Khrysalis

public protocol APIInterface: AnyObject {
    
    func getExamplePosts() -> Single<Array<Post>> 
}



